//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MapleMacro2.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.8.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LAST_OPENED_FILE {
            get {
                return ((string)(this["LAST_OPENED_FILE"]));
            }
            set {
                this["LAST_OPENED_FILE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection RECENTLY_OPENED_FILES {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["RECENTLY_OPENED_FILES"]));
            }
            set {
                this["RECENTLY_OPENED_FILES"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MapleStory")]
        public string SELECTED_GAME_TITLE {
            get {
                return ((string)(this["SELECTED_GAME_TITLE"]));
            }
            set {
                this["SELECTED_GAME_TITLE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Send {Alt down}\r\nSleep 100\r\nSend {Alt up}\r\nSleep 100\r\nSend {Alt down}\r\nSleep 100\r" +
            "\nSend {Alt up}\r\nSleep 350\r\nSend {Ctrl}")]
        public string SCRIPT_공격패턴_1 {
            get {
                return ((string)(this["SCRIPT_공격패턴_1"]));
            }
            set {
                this["SCRIPT_공격패턴_1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Send {Alt down}\r\nSleep 100\r\nSend {Alt up}\r\nSleep 100\r\nSend {Alt down}\r\nSleep 100\r" +
            "\nSend {Alt up}\r\nSleep 350\r\nSend {Ctrl}")]
        public string SCRIPT_공격패턴_2 {
            get {
                return ((string)(this["SCRIPT_공격패턴_2"]));
            }
            set {
                this["SCRIPT_공격패턴_2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2000")]
        public int MACRO_TIMER_INTERVAL {
            get {
                return ((int)(this["MACRO_TIMER_INTERVAL"]));
            }
            set {
                this["MACRO_TIMER_INTERVAL"] = value;
            }
        }
    }
}
