//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MapleMacro2.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.8.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public string 기술_1_실행간격 {
            get {
                return ((string)(this["기술_1_실행간격"]));
            }
            set {
                this["기술_1_실행간격"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public string 기술_2_실행간격 {
            get {
                return ((string)(this["기술_2_실행간격"]));
            }
            set {
                this["기술_2_실행간격"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public string 기술_3_실행간격 {
            get {
                return ((string)(this["기술_3_실행간격"]));
            }
            set {
                this["기술_3_실행간격"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public string 기술_4_실행간격 {
            get {
                return ((string)(this["기술_4_실행간격"]));
            }
            set {
                this["기술_4_실행간격"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool 기술_1_매크로유무 {
            get {
                return ((bool)(this["기술_1_매크로유무"]));
            }
            set {
                this["기술_1_매크로유무"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool 기술_2_매크로유무 {
            get {
                return ((bool)(this["기술_2_매크로유무"]));
            }
            set {
                this["기술_2_매크로유무"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool 기술_3_매크로유무 {
            get {
                return ((bool)(this["기술_3_매크로유무"]));
            }
            set {
                this["기술_3_매크로유무"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool 기술_4_매크로유무 {
            get {
                return ((bool)(this["기술_4_매크로유무"]));
            }
            set {
                this["기술_4_매크로유무"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public string 설정_매크로_활성_시간 {
            get {
                return ((string)(this["설정_매크로_활성_시간"]));
            }
            set {
                this["설정_매크로_활성_시간"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public global::System.Windows.Forms.Keys 설정_시작_키 {
            get {
                return ((global::System.Windows.Forms.Keys)(this["설정_시작_키"]));
            }
            set {
                this["설정_시작_키"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public global::System.Windows.Forms.Keys 설정_종료_키 {
            get {
                return ((global::System.Windows.Forms.Keys)(this["설정_종료_키"]));
            }
            set {
                this["설정_종료_키"] = value;
            }
        }
    }
}
